
<!DOCTYPE html>
<html>
<head>

  <meta charset="UTF-8">
  <title>SEARCH-SEMANTIC WEB</title>
  <link rel="stylesheet" type="text/css" href="css/style-eco.css">

</head>
<body>

	<div class="conteudo"> <!-- div de conteiner -->
		
		<div class="header">
			<div class="cabeca">
				<img src="IMAGEM/searchsemanticweb.jpg" alt="universo" class="img_cabeca">
			</div>
			<div class="menuitens">
				<ul>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
				</ul>
			</div>
		</div>